language: node_js
node_js:
- '0.10'
before_install:
- currentfolder=${PWD##*/}
- if [ "$currentfolder" != 'generator-newsapp' ]; then cd .. && eval "mv $currentfolder
  generator-newsapp" && cd generator-newsapp; fi
deploy:
  api_key:
    secure: MAW9t9hDKeLmY6f/xZu0NZzfGfJXMWm2jZcXUlzQtjhl8wUYKxvQyU4IF/bntQ1OeEG96scrJOsfgXD/jZd7cG2vFC+SM5PHXhodshf7PFcGubwirYrdRklcM3XzXvx6w+uRyFlIq0GqRyFWwtYEv5ceSgxZn2LEIbj8SSj3JRg=
  email: aaron.colby.williams@gmail.com
  provider: npm
